title: Frezoow'sBlog
description: This's presonal blog, I'll share my opinion of the UE/UX and the other things by internet.
author: zzoo
avatar: /logo.png
email: oowejor@pm.me

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

skin: sunrise

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
google_analytics: UA-110160306-1

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: none
  card: summary
logo: logo.png
social:
  name: 
  links:
    - https://github.com/frezoow.github.com
# google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
